// Translations
const translations = {
  "en": {
    "title": "Tajweed",
    "decreaseFont": "Decrease Font Size",
    "increaseFont": "Increase Font Size",
    "tajweedNone": "No tajweed",
    "tajweedColors": "Colors",
    "tajweedColorsAndAbbr": "Colors and Abbrevations",
    "juz": "Juz",
    "page": "Page",
    "legendTitle": "Tajweed Legend",
    "ghunna": "Ghunna: Nasalization",
    "maddMuttasil": "Madd Muttasil (Connected)",
    "maddMunfasil": "Madd Munfasil (Separated)",
    "maddArid": "Madd 'Arid (Temporary)",
    "maddLiin": "Madd Liin: Soft Elongation",
    "maddAsli": "Madd Asli: Natural Elongation (2)",
    "qalqalah": "Qalqalah: Echoing Sound",
    "iqlab": "Iqlab: Flipping",
    "silatHa": "Silat Ha: Connecting Elongation",
    "idghamGhunna": "Idgham bi Ghunna",
    "idghamBila": "Idgham bila Ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: Hiding",
    "qasr": "Qasr: Shortening",
    "med": "Med",
    "prevPage": "Previous »",
    "nextPage": "« Next",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam",
    "surahNames": {
      "1": "Al-Fatiha",
      "2": "Al-Baqarah",
      "3": "Al-Imran",
      "4": "An-Nisa",
      "5": "Al-Ma'idah",
      "6": "Al-An'am",
      "7": "Al-A'raf",
      "8": "Al-Anfal",
      "9": "At-Tawbah",
      "10": "Yunus",
      "11": "Hud",
      "12": "Yusuf",
      "13": "Ar-Ra'd",
      "14": "Ibrahim",
      "15": "Al-Hijr",
      "16": "An-Nahl",
      "17": "Al-Isra",
      "18": "Al-Kahf",
      "19": "Maryam",
      "20": "Taha",
      "21": "Al-Anbiya",
      "22": "Al-Hajj",
      "23": "Al-Mu'minun",
      "24": "An-Nur",
      "25": "Al-Furqan",
      "26": "Ash-Shu'ara",
      "27": "An-Naml",
      "28": "Al-Qasas",
      "29": "Al-Ankabut",
      "30": "Ar-Rum",
      "31": "Luqman",
      "32": "As-Sajdah",
      "33": "Al-Ahzab",
      "34": "Saba",
      "35": "Fatir",
      "36": "Ya-Sin",
      "37": "As-Saffat",
      "38": "Sad",
      "39": "Az-Zumar",
      "40": "Ghafir",
      "41": "Fussilat",
      "42": "Ash-Shura",
      "43": "Az-Zukhruf",
      "44": "Ad-Dukhan",
      "45": "Al-Jathiyah",
      "46": "Al-Ahqaf",
      "47": "Muhammad",
      "48": "Al-Fath",
      "49": "Al-Hujurat",
      "50": "Qaf",
      "51": "Adh-Dhariyat",
      "52": "At-Tur",
      "53": "An-Najm",
      "54": "Al-Qamar",
      "55": "Ar-Rahman",
      "56": "Al-Waqi'ah",
      "57": "Al-Hadid",
      "58": "Al-Mujadila",
      "59": "Al-Hashr",
      "60": "Al-Mumtahanah",
      "61": "As-Saff",
      "62": "Al-Jumu'ah",
      "63": "Al-Munafiqun",
      "64": "At-Taghabun",
      "65": "At-Talaq",
      "66": "At-Tahrim",
      "67": "Al-Mulk",
      "68": "Al-Qalam",
      "69": "Al-Haqqah",
      "70": "Al-Ma'arij",
      "71": "Nuh",
      "72": "Al-Jinn",
      "73": "Al-Muzzammil",
      "74": "Al-Muddaththir",
      "75": "Al-Qiyamah",
      "76": "Al-Insan",
      "77": "Al-Mursalat",
      "78": "An-Naba",
      "79": "An-Nazi'at",
      "80": "Abasa",
      "81": "At-Takwir",
      "82": "Al-Infitar",
      "83": "Al-Mutaffifin",
      "84": "Al-Inshiqaq",
      "85": "Al-Buruj",
      "86": "At-Tariq",
      "87": "Al-A'la",
      "88": "Al-Ghashiyah",
      "89": "Al-Fajr",
      "90": "Al-Balad",
      "91": "Ash-Shams",
      "92": "Al-Layl",
      "93": "Ad-Duha",
      "94": "Ash-Sharh",
      "95": "At-Tin",
      "96": "Al-Alaq",
      "97": "Al-Qadr",
      "98": "Al-Bayyinah",
      "99": "Az-Zalzalah",
      "100": "Al-Adiyat",
      "101": "Al-Qari'ah",
      "102": "At-Takathur",
      "103": "Al-Asr",
      "104": "Al-Humazah",
      "105": "Al-Fil",
      "106": "Quraysh",
      "107": "Al-Ma'un",
      "108": "Al-Kawthar",
      "109": "Al-Kafirun",
      "110": "An-Nasr",
      "111": "Al-Masad",
      "112": "Al-Ikhlas",
      "113": "Al-Falaq",
      "114": "An-Nas"
    }
  },
  "nl": {
    "title": "Tadjwied",
    "decreaseFont": "Lettergrootte verkleinen",
    "increaseFont": "Lettergrootte vergroten",
    "tajweedNone": "Geen tajweed",
    "tajweedColors": "Kleuren",
    "tajweedColorsAndAbbr": "Kleuren en afkortingen",
    "juz": "Joez",
    "page": "Pagina",
    "legendTitle": "Tajweed Legenda",
    "ghunna": "Ghunna: Nasalisatie",
    "maddMuttasil": "Madd Muttasil: Verbonden verlenging",
    "maddMunfasil": "Madd Munfasil: Gescheiden verlenging",
    "maddArid": "Madd 'Arid: Tijdelijke verlenging",
    "maddLiin": "Madd Liin: Zachte verlenging",
    "maddAsli": "Madd Asli: Natuurlijke verlenging (2)",
    "qalqalah": "Qalqalah: Echogend geluid",
    "iqlab": "Iqlab: Omdraaien",
    "silatHa": "Madd Silah: Verbindende verlenging",
    "idghamGhunna": "Idgham bi Ghunna",
    "idghamBila": "Idgham bila Ghunna",
    "idghamMutakaribain": "Idgham Mutakaribein",
    "idghamMithlain": "Idgham Mithlein",
    "ikhfa": "Ikhfa: Verbergen",
    "qasr": "Qasr: Verkorten",
    "med": "Med",
    "prevPage": "Vorige  »",
    "nextPage": "« Volgende",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiel",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Isjmam",
    "surahNames": {
      "1": "De Opening",
      "2": "De Koe",
      "3": "De Familie van Imran",
      "4": "De Vrouwen",
      "5": "De Tafel",
      "6": "Het Vee",
      "7": "De Kantelen",
      "8": "De Buit",
      "9": "Het Berouw",
      "10": "Jonas",
      "11": "Hud",
      "12": "Jozef",
      "13": "De Donder",
      "14": "Abraham",
      "15": "Al-Hijr",
      "16": "De Bijen",
      "17": "De Nachtreis",
      "18": "De Grot",
      "19": "Maria",
      "20": "Ta-Ha",
      "21": "De Profeten",
      "22": "De Bedevaart",
      "23": "De Gelovigen",
      "24": "Het Licht",
      "25": "Het Onderscheid",
      "26": "De Dichters",
      "27": "De Mieren",
      "28": "Het Verhaal",
      "29": "De Spin",
      "30": "De Romeinen",
      "31": "Luqman",
      "32": "De Aanbidding",
      "33": "De Partijen",
      "34": "Saba",
      "35": "De Schepper",
      "36": "Ya-Sin",
      "37": "Degenen die in de Rijen staan",
      "38": "Sad",
      "39": "De Groepen",
      "40": "De Vergever",
      "41": "De Uiteenzetting",
      "42": "De Consultatie",
      "43": "De Ornamenten",
      "44": "De Rook",
      "45": "Het Knielen",
      "46": "De Zandduinen",
      "47": "Mohammed",
      "48": "De Overwinning",
      "49": "De Kamers",
      "50": "Qaf",
      "51": "De Winden die Verspreiden",
      "52": "De Berg",
      "53": "De Ster",
      "54": "De Maan",
      "55": "De Barmhartige",
      "56": "De Gebeurtenis",
      "57": "Het IJzer",
      "58": "De Vrouw die Pleit",
      "59": "De Bijeenkomst",
      "60": "De Beproefde Vrouw",
      "61": "De Gelederen",
      "62": "De Vrijdag",
      "63": "De Huichelaars",
      "64": "Het Wederzijds Bedrog",
      "65": "De Echtscheiding",
      "66": "Het Verbod",
      "67": "De Heerschappij",
      "68": "De Pen",
      "69": "De Onvermijdelijke",
      "70": "De Manieren van Opstijging",
      "71": "Noach",
      "72": "De Djinn",
      "73": "De Ommantelde",
      "74": "De Opgewekte",
      "75": "De Opstanding",
      "76": "De Mens",
      "77": "De Uitgezondenen",
      "78": "Het Grote Nieuws",
      "79": "Degenen die Uittrekken",
      "80": "Hij Fronste",
      "81": "De Oprolling",
      "82": "De Splijting",
      "83": "De Bedriegers",
      "84": "De Scheuring",
      "85": "De Sterrenbeelden",
      "86": "De Nachtster",
      "87": "De Allerhoogste",
      "88": "De Overweldigende",
      "89": "De Dageraad",
      "90": "De Stad",
      "91": "De Zon",
      "92": "De Nacht",
      "93": "De Ochtend",
      "94": "De Verruiming",
      "95": "De Vijg",
      "96": "De Bloedklomp",
      "97": "De Waardevolle Nacht",
      "98": "Het Duidelijke Bewijs",
      "99": "De Aardbeving",
      "100": "De Renners",
      "101": "De Ramp",
      "102": "De Wedijver",
      "103": "De Tijd",
      "104": "De Lasteraar",
      "105": "De Olifant",
      "106": "Quraysh",
      "107": "De Hulp",
      "108": "De Overvloed",
      "109": "De Ongelovigen",
      "110": "De Hulp",
      "111": "De Touwvezels",
      "112": "De Zuiverheid",
      "113": "De Dageraad",
      "114": "De Mensen"
    }
  },
  "tr": {
    "title": "Tecvid",
    "decreaseFont": "Yazı Boyutunu Küçült",
    "increaseFont": "Yazı Boyutunu Büyüt",
    "tajweedNone": "Tecvidsiz",
    "tajweedColors": "Renkler",
    "tajweedColorsAndAbbr": "Renkler ve Kısaltmalar",
    "juz": "Cüz",
    "page": "Sayfa",
    "legendTitle": "Tecvid Açıklaması",
    "ghunna": "Gunne: Genizden okuma",
    "maddMuttasil": "Medd-i Muttasıl: Bitişik Med",
    "maddMunfasil": "Medd-i Munfasıl: Ayrı Med",
    "maddArid": "Medd-i 'Ârız: Geçici Med",
    "maddLiin": "Medd-i Liin: Yumuşak uzatma",
    "maddAsli": "Medd-i Tabii: Doğal uzatma (2)",
    "qalqalah": "Kalkale: Yankılı ses",
    "iqlab": "İklab: Döndürme",
    "silatHa": "Medd-i Sıla: Bağlayıcı uzatma",
    "idghamGhunna": "İdgam bi Gunne",
    "idghamBila": "İdgam bila Gunne",
    "idghamMutakaribain": "İdgam Mütekaribeyn",
    "idghamMithlain": "İdgam Misleyn",
    "ikhfa": "İhfa: Gizleme",
    "qasr": "Kasr: Kısa okuma",
    "med": "Med",
    "prevPage": "Önceki »",
    "nextPage": "« Sonraki",
    "abbrGhunna": "Gn",
    "abbrMaddMuttasil": "Mtt",
    "abbrMaddMunfasil": "Mnf",
    "abbrMaddArid": "MA",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "MS",
    "abbrMaddLazim": "Lzm",
    "abbrMaddAsli": "MT",
    "abbrQalqalah": "Kl",
    "abbrIqlab": "İkl",
    "abbrIdghamGhunna": "İmG",
    "abbrIdghamBila": "İbG",
    "abbrIdghamMithlain": "İM",
    "abbrIkhfa": "İhf",
    "abbrQasr": "Ksr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashil",
    "abbrSakta": "Sekte",
    "abbrIshmam": "İşmam",
    "surahNames": {
      "1": "Fâtiha",
      "2": "Bakara",
      "3": "Âl-i İmrân",
      "4": "Nisâ",
      "5": "Mâide",
      "6": "En'âm",
      "7": "A'râf",
      "8": "Enfâl",
      "9": "Tevbe",
      "10": "Yûnus",
      "11": "Hûd",
      "12": "Yûsuf",
      "13": "Ra'd",
      "14": "İbrâhîm",
      "15": "Hicr",
      "16": "Nahl",
      "17": "İsrâ",
      "18": "Kehf",
      "19": "Meryem",
      "20": "Tâ-Hâ",
      "21": "Enbiyâ",
      "22": "Hac",
      "23": "Mü'minûn",
      "24": "Nûr",
      "25": "Furkân",
      "26": "Şuarâ",
      "27": "Neml",
      "28": "Kasas",
      "29": "Ankebût",
      "30": "Rûm",
      "31": "Lokmân",
      "32": "Secde",
      "33": "Ahzâb",
      "34": "Sebe'",
      "35": "Fâtır",
      "36": "Yâsîn",
      "37": "Sâffât",
      "38": "Sâd",
      "39": "Zümer",
      "40": "Mü'min",
      "41": "Fussilet",
      "42": "Şûrâ",
      "43": "Zuhruf",
      "44": "Duhân",
      "45": "Câsiye",
      "46": "Ahkâf",
      "47": "Muhammed",
      "48": "Fetih",
      "49": "Hucurât",
      "50": "Kâf",
      "51": "Zâriyât",
      "52": "Tûr",
      "53": "Necm",
      "54": "Kamer",
      "55": "Rahmân",
      "56": "Vâkıa",
      "57": "Hadîd",
      "58": "Mücâdele",
      "59": "Haşr",
      "60": "Mümtehine",
      "61": "Saf",
      "62": "Cum'a",
      "63": "Münâfikûn",
      "64": "Teğâbün",
      "65": "Talâk",
      "66": "Tahrîm",
      "67": "Mülk",
      "68": "Kalem",
      "69": "Hâkka",
      "70": "Meâric",
      "71": "Nûh",
      "72": "Cin",
      "73": "Müzzemmil",
      "74": "Müddessir",
      "75": "Kıyâmet",
      "76": "İnsân",
      "77": "Mürselât",
      "78": "Nebe'",
      "79": "Nâzi'ât",
      "80": "Abese",
      "81": "Tekvîr",
      "82": "İnfitâr",
      "83": "Mutaffifîn",
      "84": "İnşikâk",
      "85": "Bürûc",
      "86": "Târık",
      "87": "A'lâ",
      "88": "Gâşiye",
      "89": "Fecr",
      "90": "Beled",
      "91": "Şems",
      "92": "Leyl",
      "93": "Duhâ",
      "94": "İnşirâh",
      "95": "Tîn",
      "96": "Alak",
      "97": "Kadr",
      "98": "Beyyine",
      "99": "Zilzâl",
      "100": "Âdiyât",
      "101": "Kâria",
      "102": "Tekâsür",
      "103": "Asr",
      "104": "Hümeze",
      "105": "Fîl",
      "106": "Kureyş",
      "107": "Mâ'ûn",
      "108": "Kevser",
      "109": "Kâfirûn",
      "110": "Nasr",
      "111": "Tebbet",
      "112": "İhlâs",
      "113": "Felak",
      "114": "Nâs"
    }
  },
  "de": {
    "title": "Tadschwid",
    "decreaseFont": "Schriftgrösse verkleinern",
    "increaseFont": "Schriftgrösse vergrössern",
    "tajweedNone": "Ohne Tadschwid",
    "tajweedColors": "Farben",
    "tajweedColorsAndAbbr": "Farben und Abkürzungen",
    "juz": "Juz",
    "page": "Seite",
    "legendTitle": "Tadschwid-Legende",
    "ghunna": "Ghunna: Nasalisierung",
    "maddMuttasil": "Madd Muttasil (verbunden)",
    "maddMunfasil": "Madd Munfasil (getrennt)",
    "maddArid": "Madd Arid (vorübergehend)",
    "maddLiin": "Madd Liin: weiche Verlängerung",
    "maddAsli": "Madd Asli: natürliche Verlängerung (2)",
    "qalqalah": "Qalqalah: Echo-Laut",
    "iqlab": "Iqlab: Umwandlung",
    "silatHa": "Silat Ha: verbindende Verlängerung",
    "idghamGhunna": "Idgham mit Ghunna",
    "idghamBila": "Idgham ohne Ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: Verbergen",
    "qasr": "Qasr: Verkürzung",
    "med": "Med",
    "prevPage": "Zurück »",
    "nextPage": "« Weiter",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "fr": {
    "title": "Tajwid",
    "decreaseFont": "Reduire la taille de police",
    "increaseFont": "Augmenter la taille de police",
    "tajweedNone": "Sans tajwid",
    "tajweedColors": "Couleurs",
    "tajweedColorsAndAbbr": "Couleurs et abreviations",
    "juz": "Juz",
    "page": "Page",
    "legendTitle": "Legende du tajwid",
    "ghunna": "Ghunna : nasalisation",
    "maddMuttasil": "Madd Muttasil (lie)",
    "maddMunfasil": "Madd Munfasil (separe)",
    "maddArid": "Madd Arid (temporaire)",
    "maddLiin": "Madd Liin : allongement doux",
    "maddAsli": "Madd Asli : allongement naturel (2)",
    "qalqalah": "Qalqalah : son rebondi",
    "iqlab": "Iqlab : conversion",
    "silatHa": "Silat Ha : allongement de liaison",
    "idghamGhunna": "Idgham avec ghunna",
    "idghamBila": "Idgham sans ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa : dissimulation",
    "qasr": "Qasr : raccourcissement",
    "med": "Med",
    "prevPage": "Precedent »",
    "nextPage": "« Suivant",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "es": {
    "title": "Tajwid",
    "decreaseFont": "Reducir tamano de fuente",
    "increaseFont": "Aumentar tamano de fuente",
    "tajweedNone": "Sin tajwid",
    "tajweedColors": "Colores",
    "tajweedColorsAndAbbr": "Colores y abreviaturas",
    "juz": "Juz",
    "page": "Pagina",
    "legendTitle": "Leyenda de tajwid",
    "ghunna": "Ghunna: nasalizacion",
    "maddMuttasil": "Madd Muttasil (conectado)",
    "maddMunfasil": "Madd Munfasil (separado)",
    "maddArid": "Madd Arid (temporal)",
    "maddLiin": "Madd Liin: elongacion suave",
    "maddAsli": "Madd Asli: elongacion natural (2)",
    "qalqalah": "Qalqalah: sonido de rebote",
    "iqlab": "Iqlab: conversion",
    "silatHa": "Silat Ha: elongacion de enlace",
    "idghamGhunna": "Idgham con ghunna",
    "idghamBila": "Idgham sin ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: ocultacion",
    "qasr": "Qasr: acortamiento",
    "med": "Med",
    "prevPage": "Anterior »",
    "nextPage": "« Siguiente",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "bs": {
    "title": "Tedzvid",
    "decreaseFont": "Smanji velicinu fonta",
    "increaseFont": "Povecaj velicinu fonta",
    "tajweedNone": "Bez tedzvida",
    "tajweedColors": "Boje",
    "tajweedColorsAndAbbr": "Boje i skracenice",
    "juz": "Dzuze",
    "page": "Stranica",
    "legendTitle": "Tedzvid legenda",
    "ghunna": "Ghunna: nazalizacija",
    "maddMuttasil": "Madd Muttasil (spojeni)",
    "maddMunfasil": "Madd Munfasil (odvojeni)",
    "maddArid": "Madd Arid (privremeni)",
    "maddLiin": "Madd Liin: blago produzenje",
    "maddAsli": "Madd Asli: prirodno produzenje (2)",
    "qalqalah": "Qalqalah: odjecni zvuk",
    "iqlab": "Iqlab: preobrazaj",
    "silatHa": "Silat Ha: povezno produzenje",
    "idghamGhunna": "Idgham sa ghunnom",
    "idghamBila": "Idgham bez ghunne",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: skrivanje",
    "qasr": "Qasr: skracivanje",
    "med": "Med",
    "prevPage": "Prethodna »",
    "nextPage": "« Sljedeca",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "el": {
    "title": "Τατζγουιντ",
    "decreaseFont": "Μειωση μεγεθους γραμματοσειρας",
    "increaseFont": "Αυξηση μεγεθους γραμματοσειρας",
    "tajweedNone": "Χωρις τατζγουιντ",
    "tajweedColors": "Χρωματα",
    "tajweedColorsAndAbbr": "Χρωματα και συντομογραφιες",
    "juz": "Juz",
    "page": "Σελιδα",
    "legendTitle": "Υπομνημα τατζγουιντ",
    "ghunna": "Ghunna: ρινικοτητα",
    "maddMuttasil": "Madd Muttasil (συνδεδεμενο)",
    "maddMunfasil": "Madd Munfasil (χωριστο)",
    "maddArid": "Madd Arid (προσωρινο)",
    "maddLiin": "Madd Liin: ηπια επιμηκυνση",
    "maddAsli": "Madd Asli: φυσικη επιμηκυνση (2)",
    "qalqalah": "Qalqalah: ηχος ηχους",
    "iqlab": "Iqlab: μετατροπη",
    "silatHa": "Silat Ha: επιμηκυνση συνδεσης",
    "idghamGhunna": "Idgham με ghunna",
    "idghamBila": "Idgham χωρις ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: αποκρυψη",
    "qasr": "Qasr: συντομευση",
    "med": "Med",
    "prevPage": "Προηγουμενη »",
    "nextPage": "« Επομενη",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "bg": {
    "title": "Таджуид",
    "decreaseFont": "Намали размера на шрифта",
    "increaseFont": "Увеличи размера на шрифта",
    "tajweedNone": "Без таджуид",
    "tajweedColors": "Цветове",
    "tajweedColorsAndAbbr": "Цветове и съкращения",
    "juz": "Джуз",
    "page": "Страница",
    "legendTitle": "Легенда на таджуид",
    "ghunna": "Гунна: назализация",
    "maddMuttasil": "Madd Muttasil (свързан)",
    "maddMunfasil": "Madd Munfasil (разделен)",
    "maddArid": "Madd Arid (временен)",
    "maddLiin": "Madd Liin: меко удължаване",
    "maddAsli": "Madd Asli: естествено удължаване (2)",
    "qalqalah": "Qalqalah: отекващ звук",
    "iqlab": "Iqlab: преобразуване",
    "silatHa": "Silat Ha: свързващо удължаване",
    "idghamGhunna": "Idgham с ghunna",
    "idghamBila": "Idgham без ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: скриване",
    "qasr": "Qasr: скъсяване",
    "med": "Med",
    "prevPage": "Предишна »",
    "nextPage": "« Следваща",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "sq": {
    "title": "Texhvid",
    "decreaseFont": "Zvogelo madhesine e shkronjave",
    "increaseFont": "Rrit madhesine e shkronjave",
    "tajweedNone": "Pa texhvid",
    "tajweedColors": "Ngjyra",
    "tajweedColorsAndAbbr": "Ngjyra dhe shkurtime",
    "juz": "Xhuz",
    "page": "Faqe",
    "legendTitle": "Legjenda e texhvidit",
    "ghunna": "Ghunna: nazalizim",
    "maddMuttasil": "Madd Muttasil (i lidhur)",
    "maddMunfasil": "Madd Munfasil (i ndare)",
    "maddArid": "Madd Arid (i perkohshem)",
    "maddLiin": "Madd Liin: zgjatje e bute",
    "maddAsli": "Madd Asli: zgjatje natyrale (2)",
    "qalqalah": "Qalqalah: tingull jehone",
    "iqlab": "Iqlab: kthim",
    "silatHa": "Silat Ha: zgjatje lidhese",
    "idghamGhunna": "Idgham me ghunna",
    "idghamBila": "Idgham pa ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: fshehje",
    "qasr": "Qasr: shkurterim",
    "med": "Med",
    "prevPage": "Faqja e meparshme »",
    "nextPage": "« Faqja tjeter",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  },
  "ru": {
    "title": "Таджвид",
    "decreaseFont": "Уменьшить размер шрифта",
    "increaseFont": "Увеличить размер шрифта",
    "tajweedNone": "Без таджвида",
    "tajweedColors": "Цвета",
    "tajweedColorsAndAbbr": "Цвета и сокращения",
    "juz": "Джуз",
    "page": "Страница",
    "legendTitle": "Легенда таджвида",
    "ghunna": "Гунна: назализация",
    "maddMuttasil": "Madd Muttasil (слитный)",
    "maddMunfasil": "Madd Munfasil (раздельный)",
    "maddArid": "Madd Arid (временный)",
    "maddLiin": "Madd Liin: мягкое удлинение",
    "maddAsli": "Madd Asli: естественное удлинение (2)",
    "qalqalah": "Qalqalah: отрывистый звук",
    "iqlab": "Iqlab: преобразование",
    "silatHa": "Silat Ha: соединительное удлинение",
    "idghamGhunna": "Idgham с ghunna",
    "idghamBila": "Idgham без ghunna",
    "idghamMutakaribain": "Idgham Mutakaribain",
    "idghamMithlain": "Idgham Mithlain",
    "ikhfa": "Ikhfa: сокрытие",
    "qasr": "Qasr: сокращение",
    "med": "Med",
    "prevPage": "Предыдущая »",
    "nextPage": "« Следующая",
    "abbrGhunna": "Gh",
    "abbrMaddMuttasil": "MM",
    "abbrMaddMunfasil": "Mn",
    "abbrMaddArid": "A",
    "abbrMaddLiin": "ML",
    "abbrSilatHa": "S",
    "abbrMaddLazim": "Lz",
    "abbrMaddAsli": "MA",
    "abbrQalqalah": "Q",
    "abbrIqlab": "Iq",
    "abbrIdghamGhunna": "IdG",
    "abbrIdghamBila": "IdB",
    "abbrIdghamMutakaribain": "IdM",
    "abbrIdghamMithlain": "Idm",
    "abbrIkhfa": "Ik",
    "abbrQasr": "Qsr",
    "abbrMed": "Med",
    "abbrTashiil": "Tashiil",
    "abbrSakta": "Sakta",
    "abbrIshmam": "Ishmam"
  }
};
