// Translations
const translations = {
  en: {
    decreaseFont: 'Decrease Font Size',
    increaseFont: 'Increase Font Size',
    rulesLabel: 'Rules',
    juz: 'Juz',
    page: 'Page',
    of: 'of',
    legendTitle: 'Tajweed Legend',
    pauseMarksTitle: 'Pause & Prostration Marks',
    ghunna: 'Ghunna: Nasalization',
    maddMuttasil: 'Madd Muttasil (Connected)',
    maddMunfasil: 'Madd Munfasil (Separated)',
    maddArid: "Madd 'Arid (Temporary)",
    maddLiin: 'Madd Liin: Soft Elongation',
    maddSilah: 'Madd Silah: Connecting Elongation',
    maddLazim: 'Madd Lazim: ',
    maddAsli: 'Madd Asli: Natural Elongation (2)',
    qalqalah: 'Qalqalah: Echoing Sound',
    iqlab: 'Iqlab: Flipping',
    silatHa: 'Silat Ha: Connecting Elongation',
    idghamGhunna: 'Idgham bi Ghunna',
    idghamBila: 'Idgham bila Ghunna',
    ikhfa: 'Ikhfa: Hiding',
    sajdah: 'Sajdah: Prostration',
    lazim: 'Lazim: Mandatory Stop',
    jaiz: 'Ja\'iz: Permissible Stop',
    waslAwla: 'Al-Wasl Awla: Better to Continue',
    waqfAwla: 'Waqf Awla: Better to Stop',
    muanaqah: 'Mu\'anaqah: Stop at one spot',
    waqfLazim: 'Waqf Lazim (Mandatory Stop)',
    waqfJaiz: 'Waqf Ja\'iz (Permissible Stop)',
    alWaslAwla: 'Al-Wasl Awla (Continuing is Better)',
    waqfAwlaTitle: 'Waqf Awla (Stopping is Better)',
    muanaqahTitle: 'Mu\'anaqah (Stop at one of two places)',
    sajdahTitle: 'Sajdah (Prostration)',
    prevPage: 'Previous »',
    nextPage: '« Next',
    surah: 'Surah',
    surahNames: {
        "1": "Al-Fatiha", "2": "Al-Baqarah", "3": "Al-Imran", "4": "An-Nisa", "5": "Al-Ma'idah",
        "6": "Al-An'am", "7": "Al-A'raf", "8": "Al-Anfal", "9": "At-Tawbah", "10": "Yunus",
        "11": "Hud", "12": "Yusuf", "13": "Ar-Ra'd", "14": "Ibrahim", "15": "Al-Hijr",
        "16": "An-Nahl", "17": "Al-Isra", "18": "Al-Kahf", "19": "Maryam", "20": "Taha",
        "21": "Al-Anbiya", "22": "Al-Hajj", "23": "Al-Mu'minun", "24": "An-Nur", "25": "Al-Furqan",
        "26": "Ash-Shu'ara", "27": "An-Naml", "28": "Al-Qasas", "29": "Al-Ankabut", "30": "Ar-Rum",
        "31": "Luqman", "32": "As-Sajdah", "33": "Al-Ahzab", "34": "Saba", "35": "Fatir",
        "36": "Ya-Sin", "37": "As-Saffat", "38": "Sad", "39": "Az-Zumar", "40": "Ghafir",
        "41": "Fussilat", "42": "Ash-Shura", "43": "Az-Zukhruf", "44": "Ad-Dukhan", "45": "Al-Jathiyah",
        "46": "Al-Ahqaf", "47": "Muhammad", "48": "Al-Fath", "49": "Al-Hujurat", "50": "Qaf",
        "51": "Adh-Dhariyat", "52": "At-Tur", "53": "An-Najm", "54": "Al-Qamar", "55": "Ar-Rahman",
        "56": "Al-Waqi'ah", "57": "Al-Hadid", "58": "Al-Mujadila", "59": "Al-Hashr", "60": "Al-Mumtahanah",
        "61": "As-Saff", "62": "Al-Jumu'ah", "63": "Al-Munafiqun", "64": "At-Taghabun", "65": "At-Talaq",
        "66": "At-Tahrim", "67": "Al-Mulk", "68": "Al-Qalam", "69": "Al-Haqqah", "70": "Al-Ma'arij",
        "71": "Nuh", "72": "Al-Jinn", "73": "Al-Muzzammil", "74": "Al-Muddaththir", "75": "Al-Qiyamah",
        "76": "Al-Insan", "77": "Al-Mursalat", "78": "An-Naba", "79": "An-Nazi'at", "80": "Abasa",
        "81": "At-Takwir", "82": "Al-Infitar", "83": "Al-Mutaffifin", "84": "Al-Inshiqaq", "85": "Al-Buruj",
        "86": "At-Tariq", "87": "Al-A'la", "88": "Al-Ghashiyah", "89": "Al-Fajr", "90": "Al-Balad",
        "91": "Ash-Shams", "92": "Al-Layl", "93": "Ad-Duha", "94": "Ash-Sharh", "95": "At-Tin",
        "96": "Al-Alaq", "97": "Al-Qadr", "98": "Al-Bayyinah", "99": "Az-Zalzalah", "100": "Al-Adiyat",
        "101": "Al-Qari'ah", "102": "At-Takathur", "103": "Al-Asr", "104": "Al-Humazah", "105": "Al-Fil",
        "106": "Quraysh", "107": "Al-Ma'un", "108": "Al-Kawthar", "109": "Al-Kafirun", "110": "An-Nasr",
        "111": "Al-Masad", "112": "Al-Ikhlas", "113": "Al-Falaq", "114": "An-Nas"
    },
    // Abbreviations
    abbrGhunna: 'Gh',
    abbrMaddMuttasil: 'MM',
    abbrMaddMunfasil: 'Mn',
    abbrMaddArid: 'A',
    abbrMaddLiin: 'ML',
    abbrSilatHa: 'S',
    abbrMaddLazim: 'Lz',
    abbrMaddAsli: 'MA',
    abbrQalqalah: 'Q',
    abbrIqlab: 'Iq',
    abbrIdghamGhunna: 'IdG',
    abbrIdghamBila: 'IdB',
    abbrIkhfa: 'Ik'
  },
  nl: {
    decreaseFont: 'Lettergrootte verkleinen',
    increaseFont: 'Lettergrootte vergroten',
    rulesLabel: 'Regels',
    juz: 'Joez',
    page: 'Pagina',
    of: 'van',
    legendTitle: 'Tajweed Legenda',
    pauseMarksTitle: 'Pauze & Prostratietekens',
    ghunna: 'Ghunna: Nasalisatie',
    maddMuttasil: 'Madd Muttasil: Verbonden verlenging',
    maddMunfasil: 'Madd Munfasil: Gescheiden verlenging',
    maddArid: "Madd 'Arid: Tijdelijke verlenging",
    maddLong: 'Madd: Lange verlenging (4-5)',
    maddLiin: 'Madd Liin: Zachte verlenging',
    silatHa: 'Madd Silah: Verbindende verlenging',
    maddLazim: 'Madd Lazim: ',
    maddAsli: 'Madd Asli: Natuurlijke verlenging (2)',
    qalqalah: 'Qalqalah: Echogend geluid',
    iqlab: 'Iqlab: Omdraaien',
    idghamGhunna: 'Idgham bi Ghunna',
    idghamBila: 'Idgham bila Ghunna',
    ikhfa: 'Ikhfa: Verbergen',
    sajdah: 'Sajdah: Prostration',
    lazim: 'Lazim: Verplichte stop',
    jaiz: 'Ja\'iz: Toegestane stop',
    waslAwla: 'Al-Wasl Awla: Beter om door te gaan',
    waqfAwla: 'Waqf Awla: Beter om te stoppen',
    muanaqah: 'Mu\'anaqah: Stop op één plek',
    waqfLazim: 'Waqf Lazim (Verplichte stop)',
    waqfJaiz: 'Waqf Ja\'iz (Toegestane stop)',
    alWaslAwla: 'Al-Wasl Awla (Doorgaan is beter)',
    waqfAwlaTitle: 'Waqf Awla (Stoppen is beter)',
    muanaqahTitle: 'Mu\'anaqah (Stop op een van twee plaatsen)',
    sajdahTitle: 'Sajdah (Prostratie)',
    prevPage: 'Vorige  »',
    nextPage: '« Volgende',
    surah: 'Soera',
    surahNames: {
        "1": "De Opening", "2": "De Koe", "3": "De Familie van Imran", "4": "De Vrouwen", "5": "De Tafel",
        "6": "Het Vee", "7": "De Kantelen", "8": "De Buit", "9": "Het Berouw", "10": "Jonas",
        "11": "Hud", "12": "Jozef", "13": "De Donder", "14": "Abraham", "15": "Al-Hijr",
        "16": "De Bijen", "17": "De Nachtreis", "18": "De Grot", "19": "Maria", "20": "Ta-Ha",
        "21": "De Profeten", "22": "De Bedevaart", "23": "De Gelovigen", "24": "Het Licht", "25": "Het Onderscheid",
        "26": "De Dichters", "27": "De Mieren", "28": "Het Verhaal", "29": "De Spin", "30": "De Romeinen",
        "31": "Luqman", "32": "De Aanbidding", "33": "De Partijen", "34": "Saba", "35": "De Schepper",
        "36": "Ya-Sin", "37": "Degenen die in de Rijen staan", "38": "Sad", "39": "De Groepen", "40": "De Vergever",
        "41": "De Uiteenzetting", "42": "De Consultatie", "43": "De Ornamenten", "44": "De Rook", "45": "Het Knielen",
        "46": "De Zandduinen", "47": "Mohammed", "48": "De Overwinning", "49": "De Kamers", "50": "Qaf",
        "51": "De Winden die Verspreiden", "52": "De Berg", "53": "De Ster", "54": "De Maan", "55": "De Barmhartige",
        "56": "De Gebeurtenis", "57": "Het IJzer", "58": "De Vrouw die Pleit", "59": "De Bijeenkomst", "60": "De Beproefde Vrouw",
        "61": "De Gelederen", "62": "De Vrijdag", "63": "De Huichelaars", "64": "Het Wederzijds Bedrog", "65": "De Echtscheiding",
        "66": "Het Verbod", "67": "De Heerschappij", "68": "De Pen", "69": "De Onvermijdelijke", "70": "De Manieren van Opstijging",
        "71": "Noach", "72": "De Djinn", "73": "De Ommantelde", "74": "De Opgewekte", "75": "De Opstanding",
        "76": "De Mens", "77": "De Uitgezondenen", "78": "Het Grote Nieuws", "79": "Degenen die Uittrekken", "80": "Hij Fronste",
        "81": "De Oprolling", "82": "De Splijting", "83": "De Bedriegers", "84": "De Scheuring", "85": "De Sterrenbeelden",
        "86": "De Nachtster", "87": "De Allerhoogste", "88": "De Overweldigende", "89": "De Dageraad", "90": "De Stad",
        "91": "De Zon", "92": "De Nacht", "93": "De Ochtend", "94": "De Verruiming", "95": "De Vijg",
        "96": "De Bloedklomp", "97": "De Waardevolle Nacht", "98": "Het Duidelijke Bewijs", "99": "De Aardbeving", "100": "De Renners",
        "101": "De Ramp", "102": "De Wedijver", "103": "De Tijd", "104": "De Lasteraar", "105": "De Olifant",
        "106": "Quraysh", "107": "De Hulp", "108": "De Overvloed", "109": "De Ongelovigen", "110": "De Hulp",
        "111": "De Touwvezels", "112": "De Zuiverheid", "113": "De Dageraad", "114": "De Mensen"
    },
    // Abbreviations
    abbrGhunna: 'Gh',
    abbrMaddMuttasil: 'MM',
    abbrMaddMunfasil: 'Mn',
    abbrMaddArid: 'A',
    abbrMaddLiin: 'ML',
    abbSilatHa: 'S',
    abbrMaddLazim: 'Lz',
    abbrMaddAsli: 'MA',
    abbrQalqalah: 'Q',
    abbrIqlab: 'Iq',
    abbrIdghamGhunna: 'IdG',
    abbrIdghamBila: 'IdB',
    abbrIkhfa: 'Ik',
  },
  tr: {
    decreaseFont: 'Yazı Boyutunu Küçült',
    increaseFont: 'Yazı Boyutunu Büyüt',
    rulesLabel: 'Tecvid',
    juz: 'Cüz',
    page: 'Sayfa',
    of: '/',
    legendTitle: 'Tecvid Açıklaması',
    pauseMarksTitle: 'Duraklama & Secde İşaretleri',
    ghunna: 'Gunne: Genizden okuma',
    maddMuttasil: 'Medd-i Muttasıl: Bitişik Med',
    maddMunfasil: 'Medd-i Munfasıl: Ayrı Med',
    maddArid: "Medd-i 'Ârız: Geçici Med",
    maddLong: 'Medd: Uzun uzatma (4-5)',
    maddLiin: 'Medd-i Liin: Yumuşak uzatma',
    silatHa: 'Medd-i Sıla: Bağlayıcı uzatma',
    maddLazim: 'Medd-i Lazim:',
    maddAsli: 'Medd-i Tabii: Doğal uzatma (2)',
    qalqalah: 'Kalkale: Yankılı ses',
    iqlab: 'İklab: Döndürme',
    idghamGhunna: 'İdgam bi Gunne',
    idghamBila: 'İdgam bila Gunne',
    ikhfa: 'İhfa: Gizleme',
    sajdah: 'Secde: Tilavet secdesi',
    lazim: 'Lazım: Zorunlu durak',
    jaiz: 'Caiz: İzinli durak',
    waslAwla: 'El-Vasl Evla: Devam etmek daha iyi',
    waqfAwla: 'Vakf Evla: Durmak daha iyi',
    muanaqah: 'Muanaka: İki yerden birinde dur',
    waqfLazim: 'Vakf-ı Lazım (Zorunlu durak)',
    waqfJaiz: 'Vakf-ı Caiz (İzinli durak)',
    alWaslAwla: 'El-Vasl Evla (Devam etmek daha iyidir)',
    waqfAwlaTitle: 'Vakf Evla (Durmak daha iyidir)',
    muanaqahTitle: 'Muanaka (İki yerden birinde dur)',
    sajdahTitle: 'Secde (Secde yeri)',
    prevPage: 'Önceki »',
    nextPage: '« Sonraki',
    surah: 'Sure',
    surahNames: {
        "1": "Fâtiha", "2": "Bakara", "3": "Âl-i İmrân", "4": "Nisâ", "5": "Mâide",
        "6": "En'âm", "7": "A'râf", "8": "Enfâl", "9": "Tevbe", "10": "Yûnus",
        "11": "Hûd", "12": "Yûsuf", "13": "Ra'd", "14": "İbrâhîm", "15": "Hicr",
        "16": "Nahl", "17": "İsrâ", "18": "Kehf", "19": "Meryem", "20": "Tâ-Hâ",
        "21": "Enbiyâ", "22": "Hac", "23": "Mü'minûn", "24": "Nûr", "25": "Furkân",
        "26": "Şuarâ", "27": "Neml", "28": "Kasas", "29": "Ankebût", "30": "Rûm",
        "31": "Lokmân", "32": "Secde", "33": "Ahzâb", "34": "Sebe'", "35": "Fâtır",
        "36": "Yâsîn", "37": "Sâffât", "38": "Sâd", "39": "Zümer", "40": "Mü'min",
        "41": "Fussilet", "42": "Şûrâ", "43": "Zuhruf", "44": "Duhân", "45": "Câsiye",
        "46": "Ahkâf", "47": "Muhammed", "48": "Fetih", "49": "Hucurât", "50": "Kâf",
        "51": "Zâriyât", "52": "Tûr", "53": "Necm", "54": "Kamer", "55": "Rahmân",
        "56": "Vâkıa", "57": "Hadîd", "58": "Mücâdele", "59": "Haşr", "60": "Mümtehine",
        "61": "Saf", "62": "Cum'a", "63": "Münâfikûn", "64": "Teğâbün", "65": "Talâk",
        "66": "Tahrîm", "67": "Mülk", "68": "Kalem", "69": "Hâkka", "70": "Meâric",
        "71": "Nûh", "72": "Cin", "73": "Müzzemmil", "74": "Müddessir", "75": "Kıyâmet",
        "76": "İnsân", "77": "Mürselât", "78": "Nebe'", "79": "Nâzi'ât", "80": "Abese",
        "81": "Tekvîr", "82": "İnfitâr", "83": "Mutaffifîn", "84": "İnşikâk", "85": "Bürûc",
        "86": "Târık", "87": "A'lâ", "88": "Gâşiye", "89": "Fecr", "90": "Beled",
        "91": "Şems", "92": "Leyl", "93": "Duhâ", "94": "İnşirâh", "95": "Tîn",
        "96": "Alak", "97": "Kadr", "98": "Beyyine", "99": "Zilzâl", "100": "Âdiyât",
        "101": "Kâria", "102": "Tekâsür", "103": "Asr", "104": "Hümeze", "105": "Fîl",
        "106": "Kureyş", "107": "Mâ'ûn", "108": "Kevser", "109": "Kâfirûn", "110": "Nasr",
        "111": "Tebbet", "112": "İhlâs", "113": "Felak", "114": "Nâs"
    },
    // Abbreviations
    abbrGhunna: 'Gn',
    abbrMaddLazim: 'Lz',
    abbrMaddMuttasil: 'MM',
    abbrMaddMunfasil: 'Mn',
    abbrMaddArid: 'A',
    abbrMaddLiin: 'ML',
    abbrSilatHa: 'S',
    abbrMaddAsli: 'MT',
    abbrQalqalah: 'Kl',
    abbrIqlab: 'İk',
    abbrIdghamGhunna: 'İmG',
    abbrIdghamBila: 'İbG',
    abbrIkhfa: 'İh',
  }
};
